apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-mongo-db
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: >-
      https://github.com/jvncs99-ci-cd/spring-boot-mongo-db-deployment.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
